name: pre-commit

on:
  pull_request:
    branches: 
      - dev

env:
  DBT_PROFILES_DIR: ./
  DBT_SNOWFLAKE_USERNAME: "praveenawsusohio"
  DBT_SNOWFLAKE_PW: gK43FL*Wxk6xN3zL
  DBT_SNOWFLAKE_ROLE: "accountadmin"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: feat/fmmis-001
    - uses: actions/setup-python@v1
      with:
        python-version: "3.7.x"
    - name: Install re_data and python dependencies
      run: |
        pip install dbt-core==1.3.0
        pip install dbt-snowflake==1.3.0
        pip install re_data
        pip install re_cloud

    - name: Run dbt
      run: |
        dbt --version
        dbt deps
        dbt run
        re_data run

    - name: Generate dbt docs
      run: |
        dbt docs generate
